<a href="https://colab.research.google.com/github/WalnutEagle5118/Machine-Learning/blob/YBI-Foundation-Project/Project_2_Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Diabetes.csv')

In [ ]:
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [ ]:
df.describe()


pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [ ]:
df.shape

(768, 9)

In [ ]:
df['diabetes'].value_counts()

0    500
1    268
Name: diabetes, dtype: int64

In [ ]:
df.groupby('diabetes').mean()

pregnancies     glucose  diastolic    triceps     insulin  \
diabetes                                                              
0            3.298000  109.980000  68.184000  19.664000   68.792000   
1            4.865672  141.257463  70.824627  22.164179  100.335821   

                bmi       dpf        age  
diabetes                                  
0         30.304200  0.429734  31.190000  
1         35.142537  0.550500  37.067164

In [ ]:
y = df['diabetes']

In [ ]:
y.shape

(768,)

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: diabetes, Length: 768, dtype: int64

In [ ]:
X = df.drop('diabetes',axis=1)

In [ ]:
X.shape

(768, 8)

In [ ]:
X

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0              6      148         72       35        0  33.6  0.627   50
1              1       85         66       29        0  26.6  0.351   31
2              8      183         64        0        0  23.3  0.672   32
3              1       89         66       23       94  28.1  0.167   21
4              0      137         40       35      168  43.1  2.288   33
..           ...      ...        ...      ...      ...   ...    ...  ...
763           10      101         76       48      180  32.9  0.171   63
764            2      122         70       27        0  36.8  0.340   27
765            5      121         72       23      112  26.2  0.245   30
766            1      126         60        0        0  30.1  0.349   47
767            1       93         70       31        0  30.4  0.315   23

[768 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mm = MinMaxScaler()

In [ ]:
X = mm.fit_transform(X)

In [ ]:
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test , y_train, y_test = train_test_split(X,y, test_size=0.3,stratify=y,random_state=69)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((537, 8), (231, 8), (537,), (231,))

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
y_pred.shape

(231,)

In [ ]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
lr.predict_proba(X_test)

array([[0.75661114, 0.24338886],
       [0.75011484, 0.24988516],
       [0.30863259, 0.69136741],
       [0.78640346, 0.21359654],
       [0.86826602, 0.13173398],
       [0.80008098, 0.19991902],
       [0.6725679 , 0.3274321 ],
       [0.82027296, 0.17972704],
       [0.61909477, 0.38090523],
       [0.72980562, 0.27019438],
       [0.80792883, 0.19207117],
       [0.4618891 , 0.5381109 ],
       [0.83507296, 0.16492704],
       [0.74250822, 0.25749178],
       [0.88146519, 0.11853481],
       [0.73252906, 0.26747094],
       [0.55477993, 0.44522007],
       [0.89638825, 0.10361175],
       [0.32327163, 0.67672837],
       [0.79216472, 0.20783528],
       [0.84671157, 0.15328843],
       [0.60646032, 0.39353968],
       [0.62999935, 0.37000065],
       [0.44813556, 0.55186444],
       [0.71040529, 0.28959471],
       [0.72521521, 0.27478479],
       [0.63935458, 0.36064542],
       [0.76638383, 0.23361617],
       [0.87588078, 0.12411922],
       [0.91849277, 0.08150723],
       [0.

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[141   9]
 [ 40  41]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.94      0.85       150
           1       0.82      0.51      0.63        81

    accuracy                           0.79       231
   macro avg       0.80      0.72      0.74       231
weighted avg       0.79      0.79      0.77       231



#  Get Future Predictions

In [ ]:
x_new = df.sample(1)

In [ ]:
x_new


pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
636            5      104         74        0        0  28.8  0.153   48   

     diabetes  
636         0

In [ ]:
x_new.shape

(1, 9)

In [ ]:
x_new = x_new.drop('diabetes',axis=1)

In [ ]:
x_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
636            5      104         74        0        0  28.8  0.153   48

In [ ]:
x_new.shape

(1, 8)

In [ ]:
x_new = mm.fit_transform(x_new)

In [ ]:
y_pred_new = lr.predict(x_new)

In [ ]:
y_pred_new


array([0])

In [ ]:
lr.predict_proba(x_new)

array([[0.99428632, 0.00571368]])

# Predicted and Actual Class is Zero(0) that is Non-Diabetic